spring:
  application:
    name: RATING-SERVICE
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      database: microservices
      host: localhost
      port: 27017


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka



server:
  port: 8083